# Site settings
title: cwndr.ws
email: charlie@cwndr.ws
description: > # this means to ignore newlines until "baseurl:"
  This is the web log for Charlie Andrews, computer programmer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cwndr.ws"
twitter_username: cwndrws
github_username:  cwandrews

# Build settings
markdown: kramdown
